name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo fmt --all -- --check

  docs_and_spell_check:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RUSTDOCFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: 'Check spelling'
        uses: crate-ci/typos@master
      - run: cargo doc --no-deps

  clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy

      - name: 'Clippy (errify + default)'
        run: cargo clippy --package errify -- -D warnings
      - name: 'Clippy (errify + anyhow)'
        run: cargo clippy --features=anyhow --no-default-features --package errify -- -D warnings
      - name: 'Clippy (errify + eyre)'
        run: cargo clippy --features=eyre --no-default-features --package errify -- -D warnings

      - name: 'Clippy (errify-macros + default)'
        run: cargo clippy --package errify-macros -- -D warnings
      - name: 'Clippy (errify-macros + anyhow)'
        run: cargo clippy --features=anyhow --no-default-features --package errify-macros -- -D warnings
      - name: 'Clippy (errify-macros + eyre)'
        run: cargo clippy --features=eyre --no-default-features --package errify-macros -- -D warnings

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@nextest

      - name: 'Test (errify + default)'
        run: cargo nextest run --package errify
      - name: 'Test (errify + anyhow)'
        run: cargo nextest run --features=anyhow --no-default-features --package errify
      - name: 'Test (errify + eyre)'
        run: cargo nextest run --features=eyre --no-default-features --package errify

      - name: 'Test (errify-macros + default)'
        run: cargo nextest run --package errify-macros
      - name: 'Test (errify-macros + anyhow)'
        run: cargo nextest run --features=anyhow --no-default-features --package errify-macros
      - name: 'Test (errify-macros + eyre)'
        run: cargo nextest run --features=eyre --no-default-features --package errify-macros