name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@nextest

      - name: 'Test (errify + default)'
        run: cargo nextest run --package errify
      - name: 'Test (errify + anyhow)'
        run: cargo nextest run --features=anyhow --no-default-features --package errify
      - name: 'Test (errify + eyre)'
        run: cargo nextest run --features=eyre --no-default-features --package errify

      - name: 'Test (errify-macros + default)'
        run: cargo nextest run --package errify-macros
      - name: 'Test (errify-macros + anyhow)'
        run: cargo nextest run --features=anyhow --no-default-features --package errify-macros
      - name: 'Test (errify-macros + eyre)'
        run: cargo nextest run --features=eyre --no-default-features --package errify-macros

  semver-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: 'Check semver'
        uses: obi1kenobi/cargo-semver-checks-action@v2

  crates_io_publish:
    name: 'Publish (crates.io)'
    needs:
      - test
      - semver-checks
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: 'cargo-release Cache'
        id: cargo_release_cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/cargo-release
          key: ${{ runner.os }}-cargo-release

      - run: cargo install cargo-release
        if: steps.cargo_release_cache.outputs.cache-hit != 'true'

      - name: 'cargo login'
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}

      # allow-branch HEAD is because GitHub actions switches
      # to the tag while building, which is a detached head
      - name: 'cargo release publish'
        run: |-
          cargo release \
            publish \
            --workspace \
            --all-features \
            --allow-branch master,HEAD \
            --no-confirm \
            --no-verify \
            --execute